### ISSUE TITLE
you okay?

### ISSUE THREAD

**Issue by gnuchanos** [lukky-nl/FPS-controller-assets#1]
where is fps controller ??

**Comment by lukky-nl** [comment]
This repository just contains the assets used for my first person controller tutorial series. I usually don't just share the full code of my tutorials as it doesn't encourage learning how it works; however if you do need it for some reason I'll gladly send it to you

**Comment by gnuchanos** [comment]
bro not everyone have big screen i can't read your code in video and my first language not english i just read code not watching all video
